/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsCodeChunk {
  id: string
  filePath: string
  language: string
  chunkType: string
  name?: string
  content: string
  startLine: number
  endLine: number
  imports: Array<string>
}
export declare class Analyser {
  /**
   * Create a new Analyser from a JSON config string.
   * Pass `"{}"` for defaults.
   */
  constructor(configJson: string)
  /**
   * Walk + parse + chunk the repository at `repo_path`.
   * Returns an array of code chunk objects.
   */
  scan(repoPath: string): Array<JsCodeChunk>
  /**
   * Build Anthropic Batch API request bodies from a repository scan.
   * Returns a JSON string containing an array of `BatchRequest` objects.
   */
  buildRequests(repoPath: string): string
  /**
   * Aggregate raw JSONL results (as returned by the Batch API) back into
   * structured analysis results.  Requires a prior `scan` to map chunk IDs.
   * Returns a JSON string of `AnalysisResult[]`.
   */
  aggregateResults(repoPath: string, jsonl: string): string
  /**
   * Render analysis results (JSON string) to the given output format
   * (e.g. `"markdown"`, `"json"`, `"csv"`, `"html"`).
   */
  renderOutput(resultsJson: string, format: string): string
}
